# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    # Set up the virtual environment
    - python -m venv $READTHEDOCS_VIRTUALENV_PATH
    # Install dependencies
    - $READTHEDOCS_VIRTUALENV_PATH/bin/python -m pip install -r requirements.txt
    # Dynamically build based on the target language of the RTD project
    - |
      if [ "$READTHEDOCS_LANGUAGE" = "de" ]; then
        $READTHEDOCS_VIRTUALENV_PATH/bin/mkdocs build --config-file mkdocs.de.yml --site-dir $READTHEDOCS_OUTPUT/html
      else
        $READTHEDOCS_VIRTUALENV_PATH/bin/mkdocs build --config-file mkdocs.yml --site-dir $READTHEDOCS_OUTPUT/html
      fi
