site_name: 'RuFi - The RulesFinder'
nav:
  - 'Home':
      - 'Was ist RuFi': 'index.md'
      - 'Get RuFi': 'get-rufi/install-rufi.md'
  - 'Mit RuFi starten':
      - 'Projekt-Planung': 'work_with_rufi/project-plan.md'
      - 'Bedienungsanleitung': 'work_with_rufi/operation-manual.md'
      - 'Vorgehensweise': 'work_with_rufi/get-involved.md'
  - 'Inhalte erstellen':
      - 'Allgemeines': 'write_content/general-edit-texts.md'
      - 'Probleme': 'write_content/probleme.md'
      - 'Regeln': 'write_content/regeln.md'
      - 'Argumente': 'write_content/argumente.md'
      - 'Pro/Contra Argumentation': 'write_content/pro-contra-argumentation.md'

copyright: "Copyright &copy; 2022-2023 Joachim Feltkamp"
extra:
  generator: false
theme:
  name: material
  locale: de
  logo: img/logo.svg
  font: false
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css: [extra.css]
markdown_extensions:
  - admonition
  - footnotes



